// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMoYPfNNC6323dTm3dwKp8hp-HlKOYO2o',
    appId: '1:737527620743:web:2a02f41a960b1203ac0422',
    messagingSenderId: '737527620743',
    projectId: 'crud9-63cd9',
    authDomain: 'crud9-63cd9.firebaseapp.com',
    storageBucket: 'crud9-63cd9.appspot.com',
    measurementId: 'G-Q7HXQD6PDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0yCbOcqU0mh-b31dWecgJn__jQjKm5II',
    appId: '1:737527620743:android:10164050a26db325ac0422',
    messagingSenderId: '737527620743',
    projectId: 'crud9-63cd9',
    storageBucket: 'crud9-63cd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-IfU1tnbkL4EaQDAnLnJD2uAAXqMhEE',
    appId: '1:737527620743:ios:d6d9097301a5f276ac0422',
    messagingSenderId: '737527620743',
    projectId: 'crud9-63cd9',
    storageBucket: 'crud9-63cd9.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-IfU1tnbkL4EaQDAnLnJD2uAAXqMhEE',
    appId: '1:737527620743:ios:d6d9097301a5f276ac0422',
    messagingSenderId: '737527620743',
    projectId: 'crud9-63cd9',
    storageBucket: 'crud9-63cd9.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMoYPfNNC6323dTm3dwKp8hp-HlKOYO2o',
    appId: '1:737527620743:web:d00c6eaacb518183ac0422',
    messagingSenderId: '737527620743',
    projectId: 'crud9-63cd9',
    authDomain: 'crud9-63cd9.firebaseapp.com',
    storageBucket: 'crud9-63cd9.appspot.com',
    measurementId: 'G-133Q69RRLZ',
  );
}
